### ISSUE TITLE
KNode crashes daemonsets on node on init

### ISSUE THREAD

**Issue by luigibk** [juan-lee/knode#4]
Hi,

Thanks for creating this project. I've installed it on some of our clusters and moving docker to a different volume on AKS really mitigates the issues reported at:
https://github.com/Azure/AKS/issues/1373

My issue is that when KNode starts, after the init stage, it crashes the other daemonsets on the node, specifically in my case those are:
- Prometheus Exporter
- Node Managed Identity (https://github.com/Azure/aad-pod-identity)

Those pods cannot come back up and, unless I delete them manually, they get into a CrashLoopBackOff state. If deleted they come back up without any issues. 
This can be mitigated by human intervention when a cluster does not run the autoscaler but unfortunately this cannot be controlled if a cluster is using the autoscaler.

Also the way the other daemonsets fail is quite strange. In the case of NMI I get the following error:

```
time="2020-03-04T08:53:33Z" level=info msg="Starting nmi process. Version: 1.5.3. Build date: 2019-10-12-00:23. Log level: info."
time="2020-03-04T08:53:33Z" level=info msg="CRD lite informers started "
time="2020-03-04T08:53:33Z" level=info msg="Initialized health probe on port &[8080]"
time="2020-03-04T08:53:33Z" level=info msg="Started health probe"
time="2020-03-04T08:53:33Z" level=info msg="Listening on port 2579"
time="2020-03-04T08:53:33Z" level=fatal msg="Error creating http server: listen tcp :2579: bind: address already in use"
``` 
which I don't think is right as if the port was in use already the pod would not start after being deleted.

**Comment by juan-lee** [comment]
Interesting, in the past this wasn't a problem after a reboot. I'll investigate further and get back to you @luigibk. Thanks for reporting this!

**Comment by 4c74356b41** [comment]
@juan-lee I think I'm seeing the same, any ideas?
