### ISSUE TITLE
Not clear how to maintain this during scale

### ISSUE THREAD

**Issue by 4c74356b41** [juan-lee/knode#7]
knode should be installed with defaults first. Once the knode daemonset is installed, applying the update to move the docker data-root will be controlled by rolling update. It's currently configured to update a node at a time, with two minutes in between nodes.

Can I never scale with this? Or upgrades also not possible?

**Comment by juan-lee** [comment]
Scale and upgrade will work fine. If you add a new node the daemonset will schedule a knode pod and make the proper changes. The same is true during an upgrade.

**Comment by 4c74356b41** [comment]
okay, so whats the point of installing the default one, if it would not get applied when you scale?

**Comment by 4c74356b41** [comment]
I guess I might as well phrase this a little bit differently: do I need to use the default one, or just the tmp one would work? I'm trying to use a gitops approach to configure the cluster, so I cannot really install default and replace it with tmp version later. as nothing is done manually and gitops just applies all the manifests to the cluster

**Comment by 4c74356b41** [comment]
@juan-lee can you, please, clarify? thanks.

**Comment by juan-lee** [comment]
You shouldn't need the default one. You can just use the yaml you need.
